import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar />
                {children}
                <footer className="bg-gradient-to-b from-blue-600 to-[#09090B] py-6 text-center text-sm text-gray-300 flex flex-col gap-4 items-center justify-center">
                    <span className="font-bold">Made With ❤️ By <Link className="hover:text-slate-900" href="https://github.com/devlpr-nitish">Nitish</Link></span>

                    <div className="flex  gap-4">
                        <Link href="/" className="hover:text-slate-900 transition">Home</Link>
                        <Link href="/convert" className="hover:text-slate-900 transition">convert</Link>
                    </div>
                </footer>
                <Toaster />
            </body>
        </html>
    );
}
